modLoader="javafml"
loaderVersion="[33,)"

license="All rights reserved"
issueTrackerURL="https://github.com/M-Marvin/MCMOD-HoloStructures/issues"

[[mods]]
modId="holostructure"
version="1.5"
displayName="HoloStructure"
authors="M_Marvin"
credits="M_Marvin"
description='''Schematica-Copy modified for 1.16.5'''